title: Yash Gaitonde
name: Yash Gaitonde's Site
author: Yash Gaitonde
author_nickname: Yash Gaitonde
email: gaitonde@umich.edu
description: ""
baseurl: ""
url: "https://yashgaitonde.com"

github:
  repository_url: https://github.com/ygaitonde/ygaitonde.github.io
  branch: master

markdown: kramdown
kramdown:
  html_to_native: true
  syntax_highlighter: rouge
  input: GFM

highlighter: rouge

permalink: '/blog/:title'
post_dirs: false

plugins:
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      styles: ["post"]
      author: "Yash Gaitonde"
